### PR TITLE
Added support for altitude pro theme

### PR DESCRIPTION
**Pull request by aaronstpierre**
Hi Carrie, 

First sorry this took me so long. It's been a busy month...

Not sure if this is the sort of direction you want to go but it has the desired results. In that I've expanded your  code into a  if statement and added the appropriate add_action for the altitude theme. 

We could probably get crafty with function_exists() but maybe that's just overkill. 

Anyway let me know what you think! Also I tested it in my development environment and it works in all cases but my testing was by no means robust :) (just query monitor and my eyes to see if styles were ending up in the right place). 

Talk soon,
Aaron

### CODE REVIEW

**Comment by cdils** [comment]
Aaron - awesome. Thank you for the PR. This week is bizzare-o, but I'll test soon.

**Comment by aaronstpierre** [comment]
You're welcome!! Ok sounds good talk soon!



—
Aaron
978-828-6177

**Comment by cdils** [comment]
I’m lame because I still haven’t responded with this.

**Comment by aaronstpierre** [comment]
heheeh :) no worries with all that's been going on with wordpress these days I've been super busy too!!!

**Comment by cdils** [comment]
@aaronstpierre I opted for a little different tact. H/T to you for getting me going in the right direction!

**Comment by aaronstpierre** [comment]
Awesome! I like it much easier to add new themes to it :)! Have a good day!

**Pull request closed without merging**
